### ISSUE TITLE
Colors and Status don't always match

### ISSUE THREAD

**Issue by Deamon-Kid** [SockDrawer/SockSite#47]
The scoresystem seems to unsure on at least edge cases if I understand it correctly.
![image](https://cloud.githubusercontent.com/assets/919508/7278324/059520c4-e915-11e4-8918-0cd77edbb7bc.png)

Filed Under: [DiscoDefinition: Dishohate](#tag)

**Comment by AccaliaDeElementia** [comment]
i think this is resolved in the upcoming release.

Onyx can you confirm?

**Comment by Onyx47** [comment]
Not sure about the source of discrepancy so I can't confirm it's fixed yet.

I'll investigate as I switch the update mechanism to WebSockets later today.

**Comment by Deamon-Kid** [comment]
I still seem to get this:
![image](https://cloud.githubusercontent.com/assets/919508/7363162/00f9e1b6-ed76-11e4-938b-9dc9320fbbc4.png)
So it seems like this is not fixed, yet.

Filed Under: [whatever version is currently live](#tag)

**Comment by AccaliaDeElementia** [comment]
@Onyx47 with the latest version is this issue still extant?

**Comment by Onyx47** [comment]
Anyone reporting this still? This should be fine now, the discrepancy was serverside and it was fixed, AFAIK.

I'm tempted to close this.

**Comment by AccaliaDeElementia** [comment]
go ahead and close it. if it crops up again we can reopen this issue at that point
